### ISSUE TITLE
Absence of GET param seems to break Mintoken

### ISSUE THREAD

**Issue by sebsel** [Zegnat/php-mintoken#11]
I am opening this on behalf of Richard, who was at IndieWebCamp Düsseldorf this weekend. This is also the context: we didn't get Mintoken to work and we had minus 3 minutes until demo time.

The endpoint seemed to crash on an error: `array_merge()` doesn't accept `null` as a second argument. This means that in the code below, `filter_input_array(INPUT_GET, ['me' ...])` does return `null`. (Line 278)

https://github.com/Zegnat/php-mintoken/blob/5f508fb285ef334dfe37170f1ebaeed8d78130c8/endpoint.php#L265-L281

I cannot find a [mention in the spec](https://indieauth.spec.indieweb.org/#request) of the `me` param in either the POST-body nor the query string for the token request. But: [Gimme-a-token](https://gimme-a-token.5eb.nl/) does add the `me`, just in the POST-body, not the query string (which I think is the `INPUT_GET` but I am not sure how that works).

When we added a `?me=` to the endpoint URL manually, it didn't seem to work either, but that's about all the debug-time we had left.

Can you shine any light on this? Where did `me` come from and why does Mintoken think it should come from GET?

**Comment by Zegnat** [comment]
The Mintoken design is old in IndieAuth terms. It is from before 2020. You would have to go back to at least January 2020 to find the latest spec that still included a `me` parameter on the [§ 6.3.1 Token Request](https://indieauth.spec.indieweb.org/20200125/#token-request). This is because later versions of IndieAuth [dropped the `me` parameter](https://indieauth.spec.indieweb.org/20220212/#changes-from-25-january-2020-to-09-august-2020). This was done when the entire communication channel between authorization and token endpoint was scrapped from the spec.

Because Mintoken does not come with an authorization endpoint at all, it is up to the user to make sure that their chosen authorization endpoint still uses the early-2020 way of communicating and that applications that come to get a token do the same.

For history:

1. Discussions on GitHub:
   * indieweb/indieauth/issues/19
   * indieweb/indieauth/issues/44
2. PR that did the work: indieweb/indieauth/pull/49
   * Specific commit that documents the out of scope: https://github.com/indieweb/indieauth/commit/28c414ce3f064225a5fe20e14013a54a03a434d9
3. [Discussion note from the 2020-08-08 IndieAuth Pop-up](https://indieweb.org/2020/Pop-ups/IndieAuth#Notes_from_2020-08-08)

Hope that shines enough light on things! 😎
